# Generated by Django 3.1.2 on 2021-01-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_shop', '0003_auto_20210128_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_shop.category', verbose_name='Категория'),
        ),
    ]
